# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
{- if and .Values.externalSecretsOperator.enabled .Values.externalSecretsOperator.secretStore.region -}}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lfx-service.mergedLabels" (dict "context" . "resourceLabels" .Values.externalSecretsOperator.externalSecret.labels) | nindent 4 }}
  {{- $annotations := include "lfx-service.mergedAnnotations" (dict "context" . "resourceAnnotations" .Values.externalSecretsOperator.externalSecret.annotations) }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: {{ .Values.externalSecretsOperator.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.name }}
    kind: SecretStore
  target:
    name: {{ .Values.name }}
  dataFrom:
    - find:
        tags:
          service-{{ .Values.name }}: "enabled"
      rewrite:
        - merge: {}
  {{- end }}
{{- end }}
