# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
{{- if and .Values.externalSecretsOperator.enabled .Values.externalSecretsOperator.secretStore.region -}}
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lfx-service.mergedLabels" (dict "context" . "resourceLabels" .Values.externalSecretsOperator.secretStore.labels) | nindent 4 }}
  {{- $annotations := include "lfx-service.mergedAnnotations" (dict "context" . "resourceAnnotations" .Values.externalSecretsOperator.secretStore.annotations) }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
spec:
  provider:
    aws:
      service: "SecretsManager"
      region: {{ .Values.externalSecretsOperator.secretStore.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.name }}
{{- end }}
